/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.reportes;

import controlador.ConexionDB;
import java.sql.Connection;
import ui.*;
import java.net.URL;
import java.util.HashMap;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kuky
 */
public class GestionReportes extends javax.swing.JInternalFrame {

    private Connection conn;
    private final String logotipo = "logo_derecha.png";

    public JDesktopPane getDesktopPane() {
        return this.desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public GestionReportes() throws SQLException {
        initComponents();
        jlNombreUsuario.setText(Login.usuario.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jpPrincipal = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jlSubtitulo = new javax.swing.JLabel();
        jlBienvenido = new javax.swing.JLabel();
        jlNombreUsuario = new javax.swing.JLabel();
        jbMueblesHistorico = new javax.swing.JButton();
        jbInmueblesAnual = new javax.swing.JButton();
        jbMueblesAnuales = new javax.swing.JButton();
        jbInmueblesHistoricos = new javax.swing.JButton();
        jlTituloPrincipal = new javax.swing.JLabel();
        jbInmueblesHistoricosHistorico = new javax.swing.JButton();
        jbInmueblesHistoricosAnual = new javax.swing.JButton();

        setClosable(true);
        setTitle("SISPA - Reportes");

        desktopPane.setPreferredSize(new java.awt.Dimension(1150, 690));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(33, 150, 243));
        jpTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpTituloMouseDragged(evt);
            }
        });
        jpTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpTituloMousePressed(evt);
            }
        });
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlSubtitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlSubtitulo.setText("Sistema de Control de Patrimonio");
        jpTitulo.add(jlSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jlBienvenido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jlBienvenido.setText("Bienvenido: ");
        jpTitulo.add(jlBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jlNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlNombreUsuario.setText("Usuario");
        jpTitulo.add(jlNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, -1));

        jpPrincipal.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 140));

        jbMueblesHistorico.setBackground(new java.awt.Color(204, 204, 204));
        jbMueblesHistorico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbMueblesHistorico.setForeground(new java.awt.Color(33, 150, 243));
        jbMueblesHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_mueble.png"))); // NOI18N
        jbMueblesHistorico.setText("Muebles Historico");
        jbMueblesHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbMueblesHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMueblesHistoricoActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbMueblesHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 260, 90));

        jbInmueblesAnual.setBackground(new java.awt.Color(204, 204, 204));
        jbInmueblesAnual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInmueblesAnual.setForeground(new java.awt.Color(33, 150, 243));
        jbInmueblesAnual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_inmueble.png"))); // NOI18N
        jbInmueblesAnual.setText("Inmuebles Anual");
        jbInmueblesAnual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbInmueblesAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInmueblesAnualActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbInmueblesAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 270, 90));

        jbMueblesAnuales.setBackground(new java.awt.Color(204, 204, 204));
        jbMueblesAnuales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbMueblesAnuales.setForeground(new java.awt.Color(33, 150, 243));
        jbMueblesAnuales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_mueble.png"))); // NOI18N
        jbMueblesAnuales.setText("Muebles Anual ");
        jbMueblesAnuales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbMueblesAnuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMueblesAnualesActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbMueblesAnuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 260, 90));

        jbInmueblesHistoricos.setBackground(new java.awt.Color(204, 204, 204));
        jbInmueblesHistoricos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInmueblesHistoricos.setForeground(new java.awt.Color(33, 150, 243));
        jbInmueblesHistoricos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_inmueble.png"))); // NOI18N
        jbInmueblesHistoricos.setText("Inmuebles Historico");
        jbInmueblesHistoricos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbInmueblesHistoricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInmueblesHistoricosActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbInmueblesHistoricos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 270, 90));

        jlTituloPrincipal.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jlTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_informe_blanco.png"))); // NOI18N
        jlTituloPrincipal.setText("SISPA - Reportes");
        jpPrincipal.add(jlTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 340, 70));

        jbInmueblesHistoricosHistorico.setBackground(new java.awt.Color(204, 204, 204));
        jbInmueblesHistoricosHistorico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInmueblesHistoricosHistorico.setForeground(new java.awt.Color(33, 150, 243));
        jbInmueblesHistoricosHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_automotores.png"))); // NOI18N
        jbInmueblesHistoricosHistorico.setText("Muebles Mantenibles Historico");
        jbInmueblesHistoricosHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbInmueblesHistoricosHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInmueblesHistoricosHistoricoActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbInmueblesHistoricosHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 270, 90));

        jbInmueblesHistoricosAnual.setBackground(new java.awt.Color(204, 204, 204));
        jbInmueblesHistoricosAnual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInmueblesHistoricosAnual.setForeground(new java.awt.Color(33, 150, 243));
        jbInmueblesHistoricosAnual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_automotores.png"))); // NOI18N
        jbInmueblesHistoricosAnual.setText("Muebles Mantenibles Anuales");
        jbInmueblesHistoricosAnual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbInmueblesHistoricosAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInmueblesHistoricosAnualActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbInmueblesHistoricosAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 270, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTituloMouseDragged

    }//GEN-LAST:event_jpTituloMouseDragged

    private void jpTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTituloMousePressed

    }//GEN-LAST:event_jpTituloMousePressed

    private void jbMueblesHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMueblesHistoricoActionPerformed

        try {
            conn = ConexionDB.GetConnection();
            JasperReport reporte;
            JasperPrint jasperPrint;
            URL in = this.getClass().getResource("MuebleReportHistorico.jasper");
            reporte = (JasperReport) JRLoader.loadObject(in);
            HashMap<String, Object> parametros = new HashMap<String, Object>();
            parametros.clear();
            parametros.put("id_reparticion", String.valueOf(Login.usuario.getReparticion().getId()));
            parametros.put("logo", this.getClass().getResourceAsStream(logotipo));
            jasperPrint = JasperFillManager.fillReport(reporte, parametros, conn);
            JasperViewer.viewReport(jasperPrint, false);
            conn.close();
        } catch (JRException ex) {
            Logger.getLogger(GestionReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbMueblesHistoricoActionPerformed

    private void jbInmueblesAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInmueblesAnualActionPerformed
        try {
            String fecha = listaAnios(); // año seleccionado del combobox para el parametero put fecha

            conn = ConexionDB.GetConnection();
            JasperReport reporte;
            JasperPrint jasperPrint;
            URL in = this.getClass().getResource("InmuebleReportAnual.jasper");
            reporte = (JasperReport) JRLoader.loadObject(in);
            HashMap<String, Object> parametros = new HashMap<String, Object>();

            parametros.clear();

            parametros.put(
                    "id_reparticion", String.valueOf(Login.usuario.getReparticion().getId()));
            parametros.put(
                    "logo", this.getClass().getResourceAsStream(logotipo));
            parametros.put(
                    "fecha", fecha);
            jasperPrint = JasperFillManager.fillReport(reporte, parametros, conn);

            JasperViewer.viewReport(jasperPrint,
                    false);
            conn.close();
        } catch (JRException ex) {
            Logger.getLogger(GestionReportes.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(GestionReportes.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInmueblesAnualActionPerformed

    private void jbMueblesAnualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMueblesAnualesActionPerformed
        try {
            String fecha = listaAnios(); // año seleccionado del combobox para el parametero put fecha

            conn = ConexionDB.GetConnection();
            JasperReport reporte;
            JasperPrint jasperPrint;
            URL in = this.getClass().getResource("MuebleReportAnual.jasper");
            reporte = (JasperReport) JRLoader.loadObject(in);
            HashMap<String, Object> parametros = new HashMap<String, Object>();

            parametros.clear();

            parametros.put(
                    "id_reparticion", String.valueOf(Login.usuario.getReparticion().getId()));
            parametros.put(
                    "logo", this.getClass().getResourceAsStream(logotipo));
            parametros.put(
                    "fecha", fecha);
            jasperPrint = JasperFillManager.fillReport(reporte, parametros, conn);

            JasperViewer.viewReport(jasperPrint,
                    false);
            conn.close();
        } catch (JRException ex) {
            Logger.getLogger(GestionReportes.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(GestionReportes.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbMueblesAnualesActionPerformed

    private void jbInmueblesHistoricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInmueblesHistoricosActionPerformed
        try {
            conn = ConexionDB.GetConnection();
            JasperReport reporte;
            JasperPrint jasperPrint;
            URL in = this.getClass().getResource("InmuebleReportHistorico.jasper");
            reporte = (JasperReport) JRLoader.loadObject(in);
            HashMap<String, Object> parametros = new HashMap<String, Object>();
            parametros.clear();
            parametros.put("id_reparticion", String.valueOf(Login.usuario.getReparticion().getId()));
            parametros.put("logo", this.getClass().getResourceAsStream(logotipo));
            jasperPrint = JasperFillManager.fillReport(reporte, parametros, conn);
            JasperViewer.viewReport(jasperPrint, false);
            conn.close();
        } catch (JRException ex) {
            Logger.getLogger(GestionReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInmueblesHistoricosActionPerformed

    private void jbInmueblesHistoricosHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInmueblesHistoricosHistoricoActionPerformed
     try {
            conn = ConexionDB.GetConnection();
            JasperReport reporte;
            JasperPrint jasperPrint;
            URL in = this.getClass().getResource("MuebleMantenibleReportHistorico.jasper");
            reporte = (JasperReport) JRLoader.loadObject(in);
            HashMap<String, Object> parametros = new HashMap<String, Object>();
            parametros.clear();
            parametros.put("id_reparticion", String.valueOf(Login.usuario.getReparticion().getId()));
            parametros.put("logo", this.getClass().getResourceAsStream(logotipo));
            jasperPrint = JasperFillManager.fillReport(reporte, parametros, conn);
            JasperViewer.viewReport(jasperPrint, false);
            conn.close();
        } catch (JRException ex) {
            Logger.getLogger(GestionReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInmueblesHistoricosHistoricoActionPerformed

    private void jbInmueblesHistoricosAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInmueblesHistoricosAnualActionPerformed
         try {
            String fecha = listaAnios(); // año seleccionado del combobox para el parametero put fecha

            conn = ConexionDB.GetConnection();
            JasperReport reporte;
            JasperPrint jasperPrint;
            URL in = this.getClass().getResource("MuebleMantenibleReportAnual.jasper");
            reporte = (JasperReport) JRLoader.loadObject(in);
            HashMap<String, Object> parametros = new HashMap<String, Object>();

            parametros.clear();

            parametros.put(
                    "id_reparticion", String.valueOf(Login.usuario.getReparticion().getId()));
            parametros.put(
                    "logo", this.getClass().getResourceAsStream(logotipo));
            parametros.put(
                    "fecha", fecha);
            jasperPrint = JasperFillManager.fillReport(reporte, parametros, conn);

            JasperViewer.viewReport(jasperPrint,
                    false);
            conn.close();
        } catch (JRException ex) {
            Logger.getLogger(GestionReportes.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(GestionReportes.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInmueblesHistoricosAnualActionPerformed

    private String listaAnios() {
        Calendar calendar = new GregorianCalendar();
        DefaultComboBoxModel dcbmAnios;
        int i, anio;
        ArrayList<String> anios = new ArrayList<>();
        for (i = 0;
                i < 100; i++) {
            anio = calendar.get(Calendar.YEAR) - i;
            anios.add(String.valueOf(anio));
        }
        dcbmAnios = new DefaultComboBoxModel(anios.toArray());
        JComboBox jcb = new JComboBox(dcbmAnios);
        jcb.setEditable(
                false);
        JOptionPane.showMessageDialog(
                null, jcb, "SELECCIONE UNA FECHA", JOptionPane.QUESTION_MESSAGE);
        return (String) jcb.getSelectedItem();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jbInmueblesAnual;
    private javax.swing.JButton jbInmueblesHistoricos;
    private javax.swing.JButton jbInmueblesHistoricosAnual;
    private javax.swing.JButton jbInmueblesHistoricosHistorico;
    private javax.swing.JButton jbMueblesAnuales;
    private javax.swing.JButton jbMueblesHistorico;
    private javax.swing.JLabel jlBienvenido;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JLabel jlSubtitulo;
    private javax.swing.JLabel jlTituloPrincipal;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpTitulo;
    // End of variables declaration//GEN-END:variables

}
