/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.gestion;

import controlador.InmuebleControlador;
import ui.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import objeto.Inmueble;
import ui.abm.AbmInmuebles;
import static ui.gestion.Gestionable.ABM_VER;

import ui.grillas.GrillaInmuebles;

/**
 *
 * @author Kuky
 */
public class GestionInmuebles extends javax.swing.JInternalFrame implements Gestionable {

    GrillaInmuebles grillaInmuebles;
    InmuebleControlador inmuebleControlador = new InmuebleControlador();
    private ArrayList<Inmueble> inmuebles = inmuebleControlador.extraerTodosVisibles();
    private ArrayList<Inmueble> inmueblesBusqueda;
    private DefaultComboBoxModel dcbmAtributo;
    private ArrayList<String> atributos = new ArrayList();

    @Override
    public JDesktopPane getDesktopPane() {
        return this.desktopPane;
    }

    /**
     *
     * @param desktopPane
     */
    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    /**
     *
     * @throws SQLException
     */
    public GestionInmuebles() throws SQLException {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        jlNombreUsuario.setText(Login.usuario.toString());
        atributos.add("NOMBRE");
        atributos.add("EXPEDIENTE");
        atributos.add("CARACTERISTICAS");
        atributos.add("OBSERVACIONES");
        atributos.add("DOMICILIO");
        atributos.add("TIPO");
        atributos.add("REPARTICION");
        dcbmAtributo = new DefaultComboBoxModel(atributos.toArray());
        jcbAtributo.setModel(dcbmAtributo);
        actualizarGestion(inmuebles);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jpPrincipal = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jlTituloPrincipal = new javax.swing.JLabel();
        jlSubtitulo = new javax.swing.JLabel();
        jlBienvenido = new javax.swing.JLabel();
        jlNombreUsuario = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInmuebles = new javax.swing.JTable();
        jpTitulo1 = new javax.swing.JPanel();
        jbVer = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jlIconoBuscar = new javax.swing.JLabel();
        jcbAtributo = new javax.swing.JComboBox();
        jtfBuscar = new javax.swing.JTextField();

        setClosable(true);
        setTitle("SISPA - Inmuebles");
        setPreferredSize(new java.awt.Dimension(1145, 710));

        desktopPane.setPreferredSize(new java.awt.Dimension(1145, 710));

        jpPrincipal.setBackground(new java.awt.Color(251, 255, 216));
        jpPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setMinimumSize(new java.awt.Dimension(1145, 710));
        jpPrincipal.setPreferredSize(new java.awt.Dimension(1145, 710));
        jpPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(33, 150, 243));
        jpTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpTituloMouseDragged(evt);
            }
        });
        jpTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpTituloMousePressed(evt);
            }
        });
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloPrincipal.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jlTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_ajustes_blanco.png"))); // NOI18N
        jlTituloPrincipal.setText("SISPA - Inmuebles");
        jpTitulo.add(jlTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 340, 70));

        jlSubtitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlSubtitulo.setText("Sistema de Control de Patrimonio");
        jpTitulo.add(jlSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jlBienvenido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jlBienvenido.setText("Bienvenido: ");
        jpTitulo.add(jlBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jlNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlNombreUsuario.setText("Usuario");
        jpTitulo.add(jlNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, -1));

        jbVolver.setBackground(new java.awt.Color(204, 204, 204));
        jbVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(33, 150, 243));
        jbVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_volver.png"))); // NOI18N
        jbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbVolver.setPreferredSize(new java.awt.Dimension(90, 121));
        jbVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbVolverMousePressed(evt);
            }
        });
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        jpTitulo.add(jbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jpPrincipal.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 140));

        jtInmuebles.setBackground(new java.awt.Color(204, 204, 204));
        jtInmuebles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtInmuebles.setForeground(new java.awt.Color(33, 150, 243));
        jtInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtInmuebles);

        jpPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 1020, 330));

        jpTitulo1.setBackground(new java.awt.Color(33, 150, 243));
        jpTitulo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpTitulo1MouseDragged(evt);
            }
        });
        jpTitulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpTitulo1MousePressed(evt);
            }
        });
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpPrincipal.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1170, 140));

        jbVer.setBackground(new java.awt.Color(204, 204, 204));
        jbVer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbVer.setForeground(new java.awt.Color(33, 150, 243));
        jbVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_ver.png"))); // NOI18N
        jbVer.setText("Ver");
        jbVer.setPreferredSize(new java.awt.Dimension(92, 33));
        jbVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 130, 40));

        jbNuevo.setBackground(new java.awt.Color(204, 204, 204));
        jbNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbNuevo.setForeground(new java.awt.Color(33, 150, 243));
        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_nuevo.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.setPreferredSize(new java.awt.Dimension(92, 33));
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 530, 130, 40));

        jbModificar.setBackground(new java.awt.Color(204, 204, 204));
        jbModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbModificar.setForeground(new java.awt.Color(33, 150, 243));
        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_modificar.png"))); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 130, 40));

        jbEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jbEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbEliminar.setForeground(new java.awt.Color(33, 150, 243));
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_eliminar.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.setPreferredSize(new java.awt.Dimension(92, 33));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 130, 40));

        jlIconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_search.png"))); // NOI18N
        jpPrincipal.add(jlIconoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jcbAtributo.setBackground(new java.awt.Color(204, 204, 204));
        jcbAtributo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbAtributo.setForeground(new java.awt.Color(33, 150, 243));
        jcbAtributo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpPrincipal.add(jcbAtributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 220, -1));

        jtfBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jtfBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfBuscar.setForeground(new java.awt.Color(33, 150, 243));
        jtfBuscar.setName(""); // NOI18N
        jtfBuscar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtfBuscarInputMethodTextChanged(evt);
            }
        });
        jtfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarActionPerformed(evt);
            }
        });
        jtfBuscar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfBuscarPropertyChange(evt);
            }
        });
        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyTyped(evt);
            }
        });
        jpPrincipal.add(jtfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 770, -1));

        desktopPane.setLayer(jpPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1156, Short.MAX_VALUE)
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 690, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTituloMouseDragged

    }//GEN-LAST:event_jpTituloMouseDragged

    private void jpTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTituloMousePressed

    }//GEN-LAST:event_jpTituloMousePressed

    private void jpTitulo1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTitulo1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jpTitulo1MouseDragged

    private void jpTitulo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTitulo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpTitulo1MousePressed

    private void jbVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerActionPerformed
        if (jtInmuebles.getSelectedRow() > -1) {
            AbmInmuebles abmInmuebles;
            GestionInmuebles gestionInmuebles;
            try {
                if (jtfBuscar.getText().equals("")) {
                    abmInmuebles = new AbmInmuebles(ABM_VER, inmuebleControlador.extraer(inmuebles.
                            get(jtInmuebles.getSelectedRow()).getId()), this);
                } else {
                    abmInmuebles = new AbmInmuebles(ABM_VER, inmuebleControlador.extraer(inmueblesBusqueda.
                            get(jtInmuebles.getSelectedRow()).getId()), this);
                }
                gestionInmuebles = new GestionInmuebles();
                this.desktopPane.add(abmInmuebles);
                util.Util.centrarInternalVentana(gestionInmuebles, abmInmuebles);
                abmInmuebles.show();
            } catch (SQLException ex) {
                Logger.getLogger(GestionMuebles.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item");
        }
    }//GEN-LAST:event_jbVerActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        AbmInmuebles abmInmuebles;
        GestionInmuebles gestionInmuebles;
        try {
            abmInmuebles = new AbmInmuebles(ABM_ALTA, new Inmueble(), this);
            gestionInmuebles = new GestionInmuebles();
            this.desktopPane.add(abmInmuebles);
            util.Util.centrarInternalVentana(gestionInmuebles, abmInmuebles);
            abmInmuebles.show();
        } catch (SQLException ex) {
            Logger.getLogger(GestionMuebles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        if (jtInmuebles.getSelectedRow() > -1) {
            AbmInmuebles abmInmuebles;
            GestionInmuebles gestionInmuebles;
            try {
                if (jtfBuscar.getText().equals("")) {
                    abmInmuebles = new AbmInmuebles(ABM_MODIFICACION, inmuebleControlador.extraer(inmuebles.
                            get(jtInmuebles.getSelectedRow()).getId()), this);
                } else {
                    abmInmuebles = new AbmInmuebles(ABM_MODIFICACION, inmuebleControlador.extraer(inmueblesBusqueda.
                            get(jtInmuebles.getSelectedRow()).getId()), this);
                }
                gestionInmuebles = new GestionInmuebles();
                this.desktopPane.add(abmInmuebles);
                util.Util.centrarInternalVentana(gestionInmuebles, abmInmuebles);
                abmInmuebles.show();
            } catch (SQLException ex) {
                Logger.getLogger(GestionMuebles.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item");
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtInmuebles.getSelectedRow() > -1) {
            AbmInmuebles abmInmuebles;
            GestionInmuebles gestionInmuebles;
            try {
                if (jtfBuscar.getText().equals("")) {
                    abmInmuebles = new AbmInmuebles(ABM_BAJA, inmuebleControlador.extraer(inmuebles.
                            get(jtInmuebles.getSelectedRow()).getId()), this);
                } else {
                    abmInmuebles = new AbmInmuebles(ABM_BAJA, inmuebleControlador.extraer(inmueblesBusqueda.
                            get(jtInmuebles.getSelectedRow()).getId()), this);
                }
                gestionInmuebles = new GestionInmuebles();
                this.desktopPane.add(abmInmuebles);
                util.Util.centrarInternalVentana(gestionInmuebles, abmInmuebles);
                abmInmuebles.show();
            } catch (SQLException ex) {
                Logger.getLogger(GestionMuebles.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVolverMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVolverMousePressed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        this.dispose();
        util.Util.setEnabledMenues(true);
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jtfBuscarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtfBuscarInputMethodTextChanged

    }//GEN-LAST:event_jtfBuscarInputMethodTextChanged

    private void jtfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscarActionPerformed

    private void jtfBuscarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfBuscarPropertyChange

    }//GEN-LAST:event_jtfBuscarPropertyChange

    private void jtfBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyTyped
        if (jtfBuscar.getText().equals("")) {
            actualizarGestion(inmuebles);
        } else {
            int indice = jcbAtributo.getSelectedIndex();
            inmueblesBusqueda = new ArrayList<>();// LO INSTANCIO ACA PARA QUE NO SE GENERE BUSQUEDAS BASURA
            for (int i = 0; i < inmuebles.size(); i++) {
                switch (indice) {
                    case 0: //SELECCIONA NOMBRE
                        if (inmuebles.get(i).getNombre().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                    case 1: //SELECCIONA EXPEDIENTE
                        if (inmuebles.get(i).getExpediente().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                    case 2: //SELECCIONA CARACTERISTICAS
                        if (inmuebles.get(i).getCaracteristicas().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                    case 3: //SELECCIONA OBSERVACIONES
                        if (inmuebles.get(i).getObservaciones().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                    case 4: //SELECCIONA DOMICILIO
                        if (inmuebles.get(i).getDomicilio().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                    case 5: //SELECCIONA TIPO
                        if (inmuebles.get(i).getTipo().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                    case 6: //SELECCIONA REPARTICION
                        if (inmuebles.get(i).getReparticion().getNombre().contains(jtfBuscar.getText())) {
                            inmueblesBusqueda.add(inmuebles.get(i));
                        }
                        break;
                }

            }
            actualizarGestion(inmueblesBusqueda);
        }
    }//GEN-LAST:event_jtfBuscarKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbVer;
    private javax.swing.JButton jbVolver;
    private javax.swing.JComboBox jcbAtributo;
    private javax.swing.JLabel jlBienvenido;
    private javax.swing.JLabel jlIconoBuscar;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JLabel jlSubtitulo;
    private javax.swing.JLabel jlTituloPrincipal;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private javax.swing.JTable jtInmuebles;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param inmuebles
     */
    public void actualizarGestion(ArrayList<Inmueble> inmuebles) {
        grillaInmuebles = new GrillaInmuebles(inmuebles);
        jtInmuebles.setModel(grillaInmuebles);
    }

    /**
     *
     */
    @Override
    public void actualizarGestion() {
        try {
            inmuebles = inmuebleControlador.extraerTodosVisibles();
            grillaInmuebles = new GrillaInmuebles(inmuebles);
            jtInmuebles.setModel(grillaInmuebles);
        } catch (SQLException ex) {
            Logger.getLogger(GestionInmuebles.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
